file(READ src/xtd.core/src/xtd/__opaque_environment_version.cpp ENVIRONMENT_VERSION_API)
string(FIND "${ENVIRONMENT_VERSION_API}" "${XTD_VERSION}" STRING_FOUND)
if (${STRING_FOUND} EQUAL -1)
  message(NOTICE "")
  message(NOTICE "--------------------------------")
  message(NOTICE "--- Version number changed ! ---")
  message(NOTICE "--------------------------------")
  message(NOTICE "")
  
  file(WRITE src/xtd.core/src/xtd/__opaque_environment_version.cpp
    "// This code was generated by CMake script.\n"
    "//\n"
    "// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "#include \"../include/xtd/environment.h\"\n"
    "\n"
    "xtd::version xtd::environment::version() noexcept {\n"
    "  return xtd::version::parse(\"${XTD_VERSION}\");\n"
    "}\n"
  )
  
  file(WRITE .appveyor.yml
    "# This code was generated by CMake script.\n"
    "#\n"
    "# Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "version: ${XTD_VERSION}.{build}\n"
    "image: Visual Studio 2019\n"
    "\n"
    "environment:\n"
    "  matrix:\n"
    "  - BUILD_OPTION: \"Win32\"\n"
    "  - BUILD_OPTION: \"x64\"\n"
    "\n"
    "install:\n"
    "  - choco install doxygen.install\n"
    "\n"
    "build_script:\n"
    "- cmd: scripts\\appveyor\\build.cmd\n"
    "\n"
    "test_script:\n"
    "- cmd: scripts\\appveyor\\test.cmd\n"
  )
  
  file(WRITE install.sh
    "#!/usr/bin/env bash\n"
    "# This code was generated by CMake script.\n"
    "#\n"
    "# Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "export xtd_version=${XTD_VERSION}\n"
    "scripts/install/install.sh \"$@\"\n"
  )
  
  file(WRITE install.cmd
    "@echo off\n"
    ":: This code was generated by CMake script.\n"
    "::\n"
    ":: Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "set xtd_version=${XTD_VERSION}\n"
    "call scripts\\install\\install.cmd %*\n"
  )
endif()
