## @file
## @brief Contains the update xtd version number scripts.
## @remarks If you change the version of the xtd, the CMake script will detect the change automatically and update the files that need the xtd version.
## @remarks see xtd_version.cmake

################################################################################
# xtd Version

file(READ src/xtd.core/src/xtd/environment_version.cpp ENVIRONMENT_VERSION_API)
string(FIND "${ENVIRONMENT_VERSION_API}" "${XTD_VERSION}" STRING_FOUND)
if (${STRING_FOUND} EQUAL -1)
  string(REPLACE "." "_" XTD_VERSION_WITH_UNDERSCORE ${XTD_VERSION})
  message(NOTICE "")
  message(NOTICE "--------------------------------")
  message(NOTICE "--- Version number changed ! ---")
  message(NOTICE "--------------------------------")
  message(NOTICE "")
  
  file(WRITE src/xtd.core/src/xtd/environment_version.cpp
    "// This code was generated by CMake script.\n"
    "//\n"
    "// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "#include \"../include/xtd/environment.hpp\"\n"
    "\n"
    "// This check verifies that the current version is defined in the availability_versions.hpp include file.\n"
    "#if !defined(__XTD_${XTD_VERSION_WITH_UNDERSCORE}__)\n"
    "#  error \"__XTD_${XTD_VERSION_WITH_UNDERSCORE}__ not defined\"\n"
    "#endif\n"
    "\n"
    "xtd::version xtd::environment::version() noexcept {\n"
    "  return xtd::version::parse(\"${XTD_VERSION}\");\n"
    "}\n"
  )
  
  file(WRITE src/xtd.core/include/xtd/xtd_version.hpp
    "// This code was generated by CMake script.\n"
    "//\n"
    "// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "#pragma once\n"
    "#include \"availability_versions.hpp\"\n"
    "\n"
    "/// @cond\n"
    "// xtd version\n"
    "\n"
    "// xtd version definition : major.minor[.build[.revision]]\n"
    "// * major    : 0 to infinite\n"
    "// * minor    : 0 to 99\n"
    "// * build    : 0 to 99\n"
    "// * revision : 0 to 99\n"
    "\n"
    "// For example xtd 1.2.3 (major = 1, minor = 2, build = 3 and revision = -1) :\n"
    "// #define __XTD_VERSION__ 1020300\n"
    "// #define __XTD_VERSION_MAJOR__ 1\n"
    "// #define __XTD_VERSION_MINOR__ 2\n"
    "// #define __XTD_VERSION_BUILD__ 3\n"
    "// #define __XTD_VERSION_REVISION__ 0\n"
    "// #define __XTD_VERSION_STRING__ \"1.2.3\"\n"
    "\n"
    "#define __XTD_VERSION__ ${XTD_NUMERIC_VERSION}\n"
    "#define __XTD_VERSION_MAJOR__ ${XTD_VERSION_MAJOR}\n"
    "#define __XTD_VERSION_MINOR__ ${XTD_VERSION_MINOR}\n"
    "#define __XTD_VERSION_BUILD__ ${XTD_VERSION_BUILD}\n"
    "#define __XTD_VERSION_REVISION__ ${XTD_VERSION_REVISION}\n"
    "#define __XTD_VERSION_STRING__ \"${XTD_VERSION}\"\n"
    "/// @endcond\n"
  )

  file(WRITE install
    "#!/usr/bin/env bash\n"
    "# This code was generated by CMake script.\n"
    "#\n"
    "# Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "export xtd_version=${XTD_VERSION}\n"
    "scripts/install/install.sh \"$@\" 2>&1 | tee install.log\n"
    "mv install.log build/install.log\n"
  )
  
  file(WRITE install.cmd
    "@echo off\n"
    ":: This code was generated by CMake script.\n"
    "::\n"
    ":: Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "set xtd_version=${XTD_VERSION}\n"
    "call scripts\\install\\install.cmd %*\n"
  )

  file(WRITE uninstall
    "#!/usr/bin/env bash\n"
    "# This code was generated by CMake script.\n"
    "#\n"
    "# Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "export xtd_version=${XTD_VERSION}\n"
    "scripts/install/uninstall.sh \"$@\"\n"
  )
  
  file(WRITE uninstall.cmd
    "@echo off\n"
    ":: This code was generated by CMake script.\n"
    "::\n"
    ":: Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.\n"
    "\n"
    "set xtd_version=${XTD_VERSION}\n"
    "call scripts\\install\\uninstall.cmd %*\n"
  )
endif()
