assembly_title("xtd.core.unit_tests")
assembly_description("xtd.core.unit_tests contains xtd.core unit tests.")
assembly_company("Gammasoft")
assembly_configuration("Test")
assembly_product("xtd.core.unit_tests")
assembly_copyright("Copyright © Gammasoft 2023")
assembly_culture("en_US.UTF-8")
assembly_trademark("")
assembly_version("")
assembly_guid("1965d1b0-680e-4ab6-87ad-96aeae4c7224")
