#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once
#include <xtd/console_color>
#include <xtd/configuration/settings>

namespace settings_with_cmake::properties {
  /// @brief A strongly typed settings class, for storing user and system settings
  /// @details This class was auto-generated by CMake script. To add or remove a member, edit your CMakeList.txt or properties/settings.cmake file then rerun cmake tools.
  /// @remarks See [Settings](https://gammasoft71.github.io/xtd/docs/documentation/guides/xtd.core/settings) for more informations.
  class settings : public xtd::object {
  public:
    /// @name Public Constructors

    /// @{
    /// @brief Initializes a new instance of the settings_with_cmake::properties::settings class.
    /// @remarks All properties are reloaded with the last saved value.
    settings() noexcept : settings {true} {}
    /// @brief Initializes a new instance of the settings_with_cmake::properties::settings class.
    /// @param load If `true` all properties are reloaded with the last saved values; otherwise none.
    explicit settings(bool load) noexcept {
      if (load) reload();
    }
    /// @}

    /// @cond
    settings(settings&&) noexcept = default;
    settings(const settings&) noexcept = default;
    settings& operator =(const settings&) noexcept = default;
    /// @endcond

    /// @name Public Properties

    /// @{
    /// @brief Gets the back_color user setting property.
    /// @return A xtd::console_color value.
    [[nodiscard]] auto back_color() const noexcept -> const xtd::console_color& {return back_color_;}
    /// @brief Sets the back_color user setting property.
    /// @param value A xtd::console_color value.
    auto back_color(const xtd::console_color& value) noexcept -> settings& {
      back_color_ = value;
      return *this;
    }

    /// @brief Gets the fore_color user setting property.
    /// @return A xtd::console_color value.
    [[nodiscard]] auto fore_color() const noexcept -> const xtd::console_color& {return fore_color_;}
    /// @brief Sets the fore_color user setting property.
    /// @param value A xtd::console_color value.
    auto fore_color(const xtd::console_color& value) noexcept -> settings& {
      fore_color_ = value;
      return *this;
    }

    /// @brief Gets the window_width user setting property.
    /// @return A xtd::uint32 value.
    [[nodiscard]] auto window_width() const noexcept -> const xtd::uint32& {return window_width_;}
    /// @brief Sets the window_width user setting property.
    /// @param value A xtd::uint32 value.
    auto window_width(const xtd::uint32& value) noexcept -> settings& {
      window_width_ = value;
      return *this;
    }

    /// @brief Gets the window_height user setting property.
    /// @return A xtd::uint32 value.
    [[nodiscard]] auto window_height() const noexcept -> const xtd::uint32& {return window_height_;}
    /// @brief Sets the window_height user setting property.
    /// @param value A xtd::uint32 value.
    auto window_height(const xtd::uint32& value) noexcept -> settings& {
      window_height_ = value;
      return *this;
    }

    /// @brief Gets the text system setting property.
    /// @return A xtd::string value.
    [[nodiscard]] auto text() const noexcept -> xtd::string {return "Settings example";}

    /// @}

    /// @name Public Methods

    /// @{
    /// @brief Reload all properties with the last saved values.
    /// @remarks See [Settings](https://gammasoft71.github.io/xtd/docs/documentation/guides/xtd.core/settings) for more informations.
    auto reload() noexcept -> void {
      back_color_ = settings_.read("back_color", back_color_);
      fore_color_ = settings_.read("fore_color", fore_color_);
      window_width_ = settings_.read("window_width", window_width_);
      window_height_ = settings_.read("window_height", window_height_);
    }

    /// @brief Reset all properties to their default values.
    /// @remarks See [Settings](https://gammasoft71.github.io/xtd/docs/documentation/guides/xtd.core/settings) for more informations.
    auto reset() noexcept -> void {
      settings_.reset();
      *this = settings {false};
    }

    /// @brief Save all properties.
    /// @remarks See [Settings](https://gammasoft71.github.io/xtd/docs/documentation/guides/xtd.core/settings) for more informations.
    auto save() noexcept -> void {
      settings_.write("back_color", back_color_);
      settings_.write("fore_color", fore_color_);
      settings_.write("window_width", window_width_);
      settings_.write("window_height", window_height_);
      settings_.save();
    }
    /// @}

    /// @name Public Static Properties

    /// @{
    /// @brief Gets the default instance of settings.
    /// @return The default instance.
    /// @remarks At the first call all properties are reloaded with the last saved values.
    [[nodiscard]] static auto default_settings() noexcept -> settings& {
      static auto default_settings = settings {};
      return default_settings;
    }
    /// @}

  private:
    xtd::configuration::settings settings_;
    xtd::console_color back_color_ {xtd::console_color::black};
    xtd::console_color fore_color_ {xtd::console_color::white};
    xtd::uint32 window_width_ {80};
    xtd::uint32 window_height_ {25};
  };
}

#pragma endregion
