# https://docs.codecov.io/docs/codecov-yaml
coverage:
  precision: 2
  round: up
  range: "0...100"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no


ignore:
