#!/usr/bin/env bash
# This code was generated by CMake script.
#
# Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

export xtd_version=0.1.0
scripts/install/install.sh "$@"
