@echo off
:: This code was generated by CMake script.
::
:: Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

set xtd_version=0.2.0
call scripts\install\install.cmd %*
