// This file was generated by generate_sidebars.cpp
module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'documentation',
      items: [
        "documentation/3rdparties_licenses",
        {
          type: 'category',
          label: 'Design Guidelines',
          items: [
            {
              type: 'category',
              label: 'Common Design Patterns',
              items: [
                "documentation/design_guidelines/Common Design Patterns/README",
                "documentation/design_guidelines/Common Design Patterns/abstract_factory",
                "documentation/design_guidelines/Common Design Patterns/adapter",
                "documentation/design_guidelines/Common Design Patterns/bridge",
                "documentation/design_guidelines/Common Design Patterns/builder",
                "documentation/design_guidelines/Common Design Patterns/chain_of_responsibility",
                "documentation/design_guidelines/Common Design Patterns/command",
                "documentation/design_guidelines/Common Design Patterns/composite",
                "documentation/design_guidelines/Common Design Patterns/decorator",
                "documentation/design_guidelines/Common Design Patterns/facade",
                "documentation/design_guidelines/Common Design Patterns/factory_method",
                "documentation/design_guidelines/Common Design Patterns/flyweight",
                "documentation/design_guidelines/Common Design Patterns/interpreter",
                "documentation/design_guidelines/Common Design Patterns/iterator",
                "documentation/design_guidelines/Common Design Patterns/mediator",
                "documentation/design_guidelines/Common Design Patterns/memento",
                "documentation/design_guidelines/Common Design Patterns/observer",
                "documentation/design_guidelines/Common Design Patterns/prototype",
                "documentation/design_guidelines/Common Design Patterns/proxy",
                "documentation/design_guidelines/Common Design Patterns/singleton",
                "documentation/design_guidelines/Common Design Patterns/state",
                "documentation/design_guidelines/Common Design Patterns/strategy",
                "documentation/design_guidelines/Common Design Patterns/template_method",
                "documentation/design_guidelines/Common Design Patterns/visitor"
              ]
            },
            {
              type: 'category',
              label: 'Design Guidelines for Exception',
              items: [
                "documentation/design_guidelines/Design Guidelines for Exception/README",
                "documentation/design_guidelines/Design Guidelines for Exception/exception_throwing",
                "documentation/design_guidelines/Design Guidelines for Exception/exceptions_and_performance",
                "documentation/design_guidelines/Design Guidelines for Exception/using_standard_exception_types"
              ]
            },
            {
              type: 'category',
              label: 'Designing for Extensibility',
              items: [
                "documentation/design_guidelines/Designing for Extensibility/README",
                "documentation/design_guidelines/Designing for Extensibility/abstractions_abstract_types_and_interfaces",
                "documentation/design_guidelines/Designing for Extensibility/base_classes_for_implementing_abstractions",
                "documentation/design_guidelines/Designing for Extensibility/events_and_callbacks",
                "documentation/design_guidelines/Designing for Extensibility/final",
                "documentation/design_guidelines/Designing for Extensibility/non-final_classes",
                "documentation/design_guidelines/Designing for Extensibility/protected_members",
                "documentation/design_guidelines/Designing for Extensibility/virtual_members"
              ]
            },
            {
              type: 'category',
              label: 'Member Design Guidelines',
              items: [
                "documentation/design_guidelines/Member Design Guidelines/README",
                "documentation/design_guidelines/Member Design Guidelines/constructor_design",
                "documentation/design_guidelines/Member Design Guidelines/event_design",
                "documentation/design_guidelines/Member Design Guidelines/field_design",
                "documentation/design_guidelines/Member Design Guidelines/member_overloading",
                "documentation/design_guidelines/Member Design Guidelines/operator_overloads",
                "documentation/design_guidelines/Member Design Guidelines/parameter_design",
                "documentation/design_guidelines/Member Design Guidelines/property_design"
              ]
            },
            {
              type: 'category',
              label: 'Naming Guidelines',
              items: [
                "documentation/design_guidelines/Naming Guidelines/README",
                "documentation/design_guidelines/Naming Guidelines/capitalisation_conventions",
                "documentation/design_guidelines/Naming Guidelines/general_naming_conventions",
                "documentation/design_guidelines/Naming Guidelines/names_of_classes_structs_and_interfaces",
                "documentation/design_guidelines/Naming Guidelines/names_of_libraries_and_dlls",
                "documentation/design_guidelines/Naming Guidelines/names_of_namespace",
                "documentation/design_guidelines/Naming Guidelines/names_of_type_members",
                "documentation/design_guidelines/Naming Guidelines/naming_parameters",
                "documentation/design_guidelines/Naming Guidelines/naming_resources"
              ]
            },
            "documentation/design_guidelines/README",
            {
              type: 'category',
              label: 'Type Design Guidelines',
              items: [
                "documentation/design_guidelines/Type Design Guidelines/README",
                "documentation/design_guidelines/Type Design Guidelines/abstract_class_design",
                "documentation/design_guidelines/Type Design Guidelines/choosing_between_class_and_struct",
                "documentation/design_guidelines/Type Design Guidelines/enum_design",
                "documentation/design_guidelines/Type Design Guidelines/interface_design",
                "documentation/design_guidelines/Type Design Guidelines/nested_types",
                "documentation/design_guidelines/Type Design Guidelines/static_class_design",
                "documentation/design_guidelines/Type Design Guidelines/struct_design"
              ]
            },
            "documentation/design_guidelines/coding_conventions_guidelines"
          ]
        },
        {
          type: 'category',
          label: 'Development status',
          items: [
            "documentation/Development status/README",
            "documentation/Development status/development_status_cmake",
            "documentation/Development status/development_status_themes",
            "documentation/Development status/development_status_toolkits",
            "documentation/Development status/development_status_tools",
            "documentation/Development status/development_status_xtd_core",
            "documentation/Development status/development_status_xtd_drawing",
            "documentation/Development status/development_status_xtd_forms",
            "documentation/Development status/development_status_xtd_tunit"
          ]
        },
        {
          type: 'category',
          label: 'Guides',
          items: [
            {
              type: 'category',
              label: 'Get started',
              items: [
                {
                  type: 'category',
                  label: 'How to install',
                  items: [
                    "documentation/Guides/Get started/How to install/check_version"
                  ]
                },
                "documentation/Guides/Get started/hello_world"
              ]
            },
            {
              type: 'category',
              label: 'Overview',
              items: [
                {
                  type: 'category',
                  label: 'Libraries',
                  items: [
                    "documentation/Guides/Overview/Libraries/architecture",
                    "documentation/Guides/Overview/Libraries/hierarchy"
                  ]
                },
                {
                  type: 'category',
                  label: 'Tutorials',
                  items: [
                    "documentation/Guides/Overview/Tutorials/README",
                    "documentation/Guides/Overview/Tutorials/form",
                    "documentation/Guides/Overview/Tutorials/git",
                    "documentation/Guides/Overview/Tutorials/test_class",
                    "documentation/Guides/Overview/Tutorials/writing_applicaion_console",
                    "documentation/Guides/Overview/Tutorials/writing_applicaion_gui"
                  ]
                },
                "documentation/Guides/Overview/introduction_to_xtd",
                "documentation/Guides/Overview/releases_patches_and_support",
                "documentation/Guides/Overview/what_is_xtd",
                "documentation/Guides/Overview/xtd_explanations"
              ]
            },
            "documentation/Guides/README",
            {
              type: 'category',
              label: 'Tools',
              items: [
                "documentation/Guides/Tools/README"
              ]
            },
            {
              type: 'category',
              label: 'xtd.cmake',
              items: [
                {
                  type: 'category',
                  label: 'Commands',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [

                      ]
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'Overview',
                  items: [

                  ]
                }
              ]
            },
            {
              type: 'category',
              label: 'xtd.core',
              items: [
                {
                  type: 'category',
                  label: 'Collections',
                  items: [
                    "documentation/Guides/xtd.core/Collections/Selecting a Collection Class",
                    "documentation/Guides/xtd.core/Collections/overview"
                  ]
                },
                {
                  type: 'category',
                  label: 'Common I:O tasks',
                  items: [
                    {
                      type: 'category',
                      label: 'How-tos',
                      items: [
                        "documentation/Guides/xtd.core/Common I:O tasks/How-tos/copy_directories",
                        "documentation/Guides/xtd.core/Common I:O tasks/How-tos/enumerate_directories_and_files",
                        "documentation/Guides/xtd.core/Common I:O tasks/How-tos/open_and_append_to_a_log_file",
                        "documentation/Guides/xtd.core/Common I:O tasks/How-tos/read_and_write_to_a_newly_created_data_file",
                        "documentation/Guides/xtd.core/Common I:O tasks/How-tos/read_text_from_a_file",
                        "documentation/Guides/xtd.core/Common I:O tasks/How-tos/write_text_to_a_file"
                      ]
                    },
                    "documentation/Guides/xtd.core/Common I:O tasks/README",
                    "documentation/Guides/xtd.core/Common I:O tasks/file_and_stream_io",
                    "documentation/Guides/xtd.core/Common I:O tasks/write_a_text_file"
                  ]
                },
                {
                  type: 'category',
                  label: 'Entry point',
                  items: [
                    "documentation/Guides/xtd.core/Entry point/main_and_startup"
                  ]
                },
                {
                  type: 'category',
                  label: 'Events',
                  items: [
                    "documentation/Guides/xtd.core/Events/observer_design_pattern",
                    "documentation/Guides/xtd.core/Events/overview",
                    "documentation/Guides/xtd.core/Events/raise_and_consume_events"
                  ]
                },
                {
                  type: 'category',
                  label: 'Exceptions',
                  items: [
                    {
                      type: 'category',
                      label: 'How-tos',
                      items: [
                        "documentation/Guides/xtd.core/Exceptions/How-tos/create_user_defined_exceptions",
                        "documentation/Guides/xtd.core/Exceptions/How-tos/exceptions_try_catch"
                      ]
                    },
                    "documentation/Guides/xtd.core/Exceptions/exception_class_and_properties",
                    "documentation/Guides/xtd.core/Exceptions/exceptions_best_practices",
                    "documentation/Guides/xtd.core/Exceptions/overview"
                  ]
                },
                {
                  type: 'category',
                  label: 'Format number dates other types',
                  items: [
                    {
                      type: 'category',
                      label: 'How-tos',
                      items: [

                      ]
                    },
                    "documentation/Guides/xtd.core/Format number dates other types/overview",
                    "documentation/Guides/xtd.core/Format number dates other types/standard_numeric_format_strings"
                  ]
                },
                {
                  type: 'category',
                  label: 'Networking',
                  items: [
                    {
                      type: 'category',
                      label: 'Sockets',
                      items: [
                        "documentation/Guides/xtd.core/Networking/Sockets/sockets_support"
                      ]
                    },
                    "documentation/Guides/xtd.core/Networking/network_programming"
                  ]
                },
                {
                  type: 'category',
                  label: 'Parse',
                  items: [
                    "documentation/Guides/xtd.core/Parse/overview"
                  ]
                },
                {
                  type: 'category',
                  label: 'Types overview',
                  items: [
                    {
                      type: 'category',
                      label: 'Type conversion',
                      items: [
                        "documentation/Guides/xtd.core/Types overview/Type conversion/overview",
                        "documentation/Guides/xtd.core/Types overview/Type conversion/type_conversion_tables"
                      ]
                    },
                    "documentation/Guides/xtd.core/Types overview/date_time",
                    "documentation/Guides/xtd.core/Types overview/delegates",
                    "documentation/Guides/xtd.core/Types overview/enum_class",
                    "documentation/Guides/xtd.core/Types overview/events",
                    "documentation/Guides/xtd.core/Types overview/preprocessor_symbols",
                    "documentation/Guides/xtd.core/Types overview/string",
                    "documentation/Guides/xtd.core/Types overview/types"
                  ]
                },
                "documentation/Guides/xtd.core/delegates_and_lambdas",
                "documentation/Guides/xtd.core/interfaces",
                "documentation/Guides/xtd.core/internationalization",
                "documentation/Guides/xtd.core/literal_operators",
                "documentation/Guides/xtd.core/resources",
                "documentation/Guides/xtd.core/settings"
              ]
            },
            {
              type: 'category',
              label: 'xtd.drawing',
              items: [
                {
                  type: 'category',
                  label: 'Drawing',
                  items: [

                  ]
                }
              ]
            },
            {
              type: 'category',
              label: 'xtd.forms',
              items: [
                {
                  type: 'category',
                  label: 'Controls',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [
                        "documentation/Guides/xtd.forms/Controls/Common tasks/thread_safe_control_call"
                      ]
                    },
                    "documentation/Guides/xtd.forms/Controls/overview",
                    "documentation/Guides/xtd.forms/Controls/position_and_layout_of_controls"
                  ]
                },
                {
                  type: 'category',
                  label: 'Data binding',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [

                      ]
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'Forms',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [

                      ]
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'Overview',
                  items: [
                    "documentation/Guides/xtd.forms/Overview/ambient_properties",
                    "documentation/Guides/xtd.forms/Overview/application_overview",
                    "documentation/Guides/xtd.forms/Overview/control_appearance",
                    "documentation/Guides/xtd.forms/Overview/control_events",
                    "documentation/Guides/xtd.forms/Overview/controls_management",
                    "documentation/Guides/xtd.forms/Overview/size_and_location_properties",
                    "documentation/Guides/xtd.forms/Overview/xtd_forms_overview"
                  ]
                },
                {
                  type: 'category',
                  label: 'Printing',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [

                      ]
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'Style sheets',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [

                      ]
                    },
                    "documentation/Guides/xtd.forms/Style sheets/style_sheets_box_model",
                    "documentation/Guides/xtd.forms/Style sheets/style_sheets_overview",
                    "documentation/Guides/xtd.forms/Style sheets/style_sheets_reference"
                  ]
                },
                {
                  type: 'category',
                  label: 'User input - keyboard',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [

                      ]
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'User input - mouse',
                  items: [
                    {
                      type: 'category',
                      label: 'Common tasks',
                      items: [

                      ]
                    }
                  ]
                }
              ]
            },
            {
              type: 'category',
              label: 'xtd.tunit',
              items: [
                {
                  type: 'category',
                  label: 'Overview',
                  items: [
                    "documentation/Guides/xtd.tunit/Overview/tunit_overview"
                  ]
                }
              ]
            },
            "documentation/Guides/xtd_documentation"
          ]
        },
        {
          type: 'category',
          label: 'Internal',
          items: [
            "documentation/Internal/README",
            "documentation/Internal/add_new_control",
            "documentation/Internal/buy_me_a_coffee",
            "documentation/Internal/class_organization",
            "documentation/Internal/code_pages",
            {
              type: 'category',
              label: 'code_review',
              items: [
                "documentation/Internal/code_review/font_box",
                "documentation/Internal/code_review/open_file_box",
                "documentation/Internal/code_review/progress_box",
                "documentation/Internal/code_review/save_file_box"
              ]
            },
            "documentation/Internal/computer_guid",
            "documentation/Internal/default_size_of_controls",
            "documentation/Internal/default_size_of_controls_g",
            "documentation/Internal/default_size_of_controls_m",
            "documentation/Internal/default_size_of_controls_w",
            "documentation/Internal/deprecated",
            "documentation/Internal/exceptions",
            "documentation/Internal/git",
            "documentation/Internal/globalization",
            "documentation/Internal/hresults",
            "documentation/Internal/ios_build",
            "documentation/Internal/key_events",
            "documentation/Internal/process",
            "documentation/Internal/some_numbers",
            "documentation/Internal/sounds",
            "documentation/Internal/speech",
            "documentation/Internal/speedup_build",
            "documentation/Internal/theme",
            "documentation/Internal/wix_themes",
            "documentation/Internal/wxwidgets_window_styles"
          ]
        },
        {
          type: 'category',
          label: 'Portability',
          items: [
            "documentation/Portability/README",
            "documentation/Portability/cpp"
          ]
        },
        "documentation/README",
        {
          type: 'category',
          label: 'eBook',
          items: [
            "documentation/e_book/README",
            "documentation/e_book/console_classes",
            "documentation/e_book/first_programs",
            "documentation/e_book/introduction",
            "documentation/e_book/menus_and_toolbars",
            "documentation/e_book/unit_testing_classes"
          ]
        },
        "documentation/external_tools_libraries_and_toolkits",
        "documentation/features",
        "documentation/getting_started",
        "documentation/license",
        "documentation/links",
        "documentation/reference_guides",
        {
          type: 'category',
          label: 'release_notes',
          items: [
            "documentation/release_notes/v0.1.0_release_note",
            "documentation/release_notes/v0.1.1_release_note",
            "documentation/release_notes/v0.1.2_release_note",
            "documentation/release_notes/v0.2.0_release_note"
          ]
        },
        "documentation/release_notes",
        "documentation/roadmap",
        "documentation/toolkits_licenses",
        "documentation/tools",
        "documentation/translation_status"
      ]
    },
    {
      type: 'category',
      label: 'news',
      items: [
        "news/20211010",
        "news/20221118",
        "news/20230209",
        "news/20230717",
        "news/20231112",
        "news/20240312",
        "news/20250615",
        "news/20250630"
      ]
    },
    {
      type: 'category',
      label: 'Support',
      items: [
        "Support/README",
        "Support/contact"
      ]
    },
    {
      type: 'category',
      label: 'doxygen',
      items: [

      ]
    }
  ]
};
