#pragma once
#include <xtd/xtd.delegates>
#include <xtd/xtd.diagnostics>
#include <xtd/xtd.drawing>
#include <xtd/xtd.environment>
#include <xtd/xtd.io>
#include <xtd/xtd.strings>
#include <xtd/forms/window_messages.hpp>

#include "xtd/forms/layout/arranged_element_collection.hpp"
#include "xtd/forms/application.hpp"
#include "xtd/forms/application_informations.hpp"
#include "xtd/forms/border_style.hpp"
#include "xtd/forms/button.hpp"
#include "xtd/forms/cancel_event_args.hpp"
#include "xtd/forms/check_box.hpp"
#include "xtd/forms/check_state.hpp"
#include "xtd/forms/close_reason.hpp"
#include "xtd/forms/control.hpp"
#include "xtd/forms/create_params.hpp"
#include "xtd/forms/dialog_result.hpp"
#include "xtd/forms/form.hpp"
#include "xtd/forms/form_closed_event_args.hpp"
#include "xtd/forms/form_closed_event_handler.hpp"
#include "xtd/forms/form_closing_event_args.hpp"
#include "xtd/forms/form_closing_event_handler.hpp"
#include "xtd/forms/group_box.hpp"
#include "xtd/forms/key_event_args.hpp"
#include "xtd/forms/key_event_handler.hpp"
#include "xtd/forms/key_press_event_args.hpp"
#include "xtd/forms/key_press_event_handler.hpp"
#include "xtd/forms/keys.hpp"
#include "xtd/forms/label.hpp"
#include "xtd/forms/list_box.hpp"
#include "xtd/forms/message.hpp"
#include "xtd/forms/message_box.hpp"
#include "xtd/forms/message_box_buttons.hpp"
#include "xtd/forms/message_box_default_button.hpp"
#include "xtd/forms/message_box_icon.hpp"
#include "xtd/forms/message_box_options.hpp"
#include "xtd/forms/mouse_buttons.hpp"
#include "xtd/forms/mouse_event_args.hpp"
#include "xtd/forms/mouse_event_handler.hpp"
#include "xtd/forms/panel.hpp"
#include "xtd/forms/radio_button.hpp"
#include "xtd/forms/screen.hpp"
#include "xtd/forms/text_box.hpp"
#include "xtd/forms/timer.hpp"
