#pragma once
#include <xtd/xtd.delegates>
#include <xtd/xtd.diagnostics>
#include <xtd/xtd.drawing>
#include <xtd/xtd.environment>
#include <xtd/xtd.io>
#include <xtd/xtd.strings>
#include "xtd/forms/application.hpp"
#include "xtd/forms/button.hpp"
#include "xtd/forms/control.hpp"
#include "xtd/forms/form.hpp"
#include "xtd/forms/keys.hpp"
#include "xtd/forms/label.hpp"
#include "xtd/forms/message.hpp"
#include "xtd/forms/window_messages.hpp"
