#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Remarks : If this file was manually created, you need re-run cmake generator after creating
//           or modifying any parameter bellow.

#include <xtd/reflection/assembly_info>

// Information about this assembly is defined by the following attributes.
// Change them to the values specific to your project.

assembly_title_("xtd.drawing.rectangles.tests");
assembly_description_("xtd.drawing.rectangles.tests contains graphics rectangle manual tests.");
assembly_configuration_("Test");
assembly_company_("Gammasoft");
assembly_product_("xtd.drawing.rectangles.tests");
assembly_copyright_("Copyright © Gammasoft 2023");
assembly_trademark_("");
assembly_culture_("en_US.UTF-8");

// The following GUID is for the ID of the typelib if this project is exposed to COM

assembly_guid_("6058b730-376a-4b4b-9472-0b8e3f882ecf");

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// In not specify or empty or "*" the cmake project version is used.

assembly_version_("");
#pragma endregion
