#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Remarks : If this file was manually created, you need re-run cmake generator after creating
//           or modifying any parameter bellow.

#include <xtd/reflection/assembly_info>

// Information about this assembly is defined by the following attributes.
// Change them to the values specific to your project.

assembly_title_("xtdc");
assembly_description_("xtdc is s project management command line tool.");
assembly_configuration_("Debug");
assembly_company_("Gammasoft");
assembly_product_("xtdc");
assembly_copyright_("Copyright © Gammasoft 2024");
assembly_trademark_("");
assembly_culture_("en_US.UTF-8");

// The following GUID is for the ID of the typelib if this project is exposed to COM

assembly_guid_("98dd1070-5bd0-4a43-9b54-7b55379fc608");

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// In not specify or empty or "*" the cmake project version is used.

assembly_version_("");
#pragma endregion
