assembly_title("About dialog from executng assembly")
assembly_description("Create an about dialog from executng assembly informations.")
assembly_company("Gammasoft")
assembly_product("about_dialog_from_executing_assembly_informations")
assembly_copyright("Copyright © Gammasoft 2024")
assembly_trademark("")
assembly_version("1.2.3")
assembly_guid("c8fea9fd-fde5-4275-a709-204527b5188e")
