#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../src/minesweeper.h"
#include <xtd/startup.h>

startup_(minesweeper::form_minesweeper);
#pragma endregion
