#pragma once
#include <xtd/xtd.strings>
#include "drawing/color.hpp"
#include "drawing/known_color.hpp"
#include "drawing/point.hpp"
#include "drawing/point_f.hpp"
#include "drawing/rectangle.hpp"
#include "drawing/rectangle_f.hpp"
#include "drawing/size.hpp"
#include "drawing/size_f.hpp"
#include "drawing/system_colors.hpp"
