#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../src/game_of_life.h"
#include <xtd/startup.h>

startup_(game_of_life::form_game_of_life);
#pragma endregion
