#pragma once
#include <xtd/xtd.delegates>
#include <xtd/xtd.diagnostics>
#include <xtd/xtd.drawing>
#include <xtd/xtd.environment>
#include <xtd/xtd.environment>
#include <xtd/xtd.io>
#include <xtd/xtd.strings>
#include "forms/create_params.hpp"
#include "forms/window_messages.hpp"
#include "forms/native/application.hpp"
#include "forms/native/button.hpp"
#include "forms/native/check_box.hpp"
#include "forms/native/control.hpp"
#include "forms/native/form.hpp"
#include "forms/native/group_box.hpp"
#include "forms/native/label.hpp"
#include "forms/native/panel.hpp"
#include "forms/native/radio_button.hpp"
#include "forms/native/text_box.hpp"
#include "forms/native/timer.hpp"
