// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

#include "../include/xtd/environment.hpp"

// This check verifies that the current version is defined in the availability_versions.hpp include file.
#if !defined(__XTD_1_0_0__)
#  error "__XTD_1_0_0__ not defined"
#endif

xtd::version xtd::environment::version() noexcept {
  return xtd::version::parse("1.0.0");
}
