// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

#include "../include/xtd/environment.h"

xtd::version xtd::environment::version() {
  return xtd::version::parse("0.2.0");
}
