#include <xtd/console>

using namespace xtd;

auto main() -> int {
  console::write_line("This console application was generated by xtd cmake helpers.");
  console::write_line("See CMakeLists.txt file.");
}
