// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

/// @file
/// @brief Contains #core_native_export_ keyword.
/// @copyright Copyright (c) 2023 Gammasoft. All rights reserved.
#pragma once

/// @brief Define shared library export.
/// @ingroup keywords
/// @warning Internal use only
#define core_native_export_
