resource(minesweeper_ico resources/minesweeper.ico)
resource(minesweeper_png resources/minesweeper.png)
resource(flag resources/flag.png)
resource(mine resources/mine.png)
resource(smiley1 resources/smiley1.png)
resource(smiley2 resources/smiley2.png)
resource(smiley3 resources/smiley3.png)
resource(smiley4 resources/smiley4.png)
