# bitmap 1 x 1 :
resource(bitmap_1_1_bmp "resources/bitmap_1_1.bmp")
resource(bitmap_1_1_exif "resources/bitmap_1_1.exif")
resource(bitmap_1_1_gif "resources/bitmap_1_1.gif")
resource(bitmap_1_1_jpg "resources/bitmap_1_1.jpg")
resource(bitmap_1_1_png "resources/bitmap_1_1.png")
resource(bitmap_1_1_pnm "resources/bitmap_1_1.pnm")
resource(bitmap_1_1_ppm "resources/bitmap_1_1.ppm")
resource(bitmap_1_1_tiff "resources/bitmap_1_1.tiff")
resource(bitmap_1_1_xpm "resources/bitmap_1_1.xpm")

# bitmap 1 x 2 :
resource(bitmap_1_2_bmp "resources/bitmap_1_2.bmp")
resource(bitmap_1_2_exif "resources/bitmap_1_2.exif")
resource(bitmap_1_2_gif "resources/bitmap_1_2.gif")
resource(bitmap_1_2_jpg "resources/bitmap_1_2.jpg")
resource(bitmap_1_2_png "resources/bitmap_1_2.png")
resource(bitmap_1_2_pnm "resources/bitmap_1_2.pnm")
resource(bitmap_1_2_ppm "resources/bitmap_1_2.ppm")
resource(bitmap_1_2_tiff "resources/bitmap_1_2.tiff")
resource(bitmap_1_2_xpm "resources/bitmap_1_2.xpm")

# bitmap 1 x 3 :
resource(bitmap_1_3_bmp "resources/bitmap_1_3.bmp")
resource(bitmap_1_3_exif "resources/bitmap_1_3.exif")
resource(bitmap_1_3_gif "resources/bitmap_1_3.gif")
resource(bitmap_1_3_jpg "resources/bitmap_1_3.jpg")
resource(bitmap_1_3_png "resources/bitmap_1_3.png")
resource(bitmap_1_3_ppn "resources/bitmap_1_3.pnm")
resource(bitmap_1_3_ppm "resources/bitmap_1_3.ppm")
resource(bitmap_1_3_tiff "resources/bitmap_1_3.tiff")
resource(bitmap_1_3_xpm "resources/bitmap_1_3.xpm")

# bitmap 1 x 4 :
resource(bitmap_1_4_bmp "resources/bitmap_1_4.bmp")
resource(bitmap_1_4_exif "resources/bitmap_1_4.exif")
resource(bitmap_1_4_gif "resources/bitmap_1_4.gif")
resource(bitmap_1_4_jpg "resources/bitmap_1_4.jpg")
resource(bitmap_1_4_png "resources/bitmap_1_4.png")
resource(bitmap_1_4_pnm "resources/bitmap_1_4.pnm")
resource(bitmap_1_4_ppm "resources/bitmap_1_4.ppm")
resource(bitmap_1_4_tiff "resources/bitmap_1_4.tiff")
resource(bitmap_1_4_xpm "resources/bitmap_1_4.xpm")

# bitmap 2 x 1 :
resource(bitmap_2_1_bmp "resources/bitmap_2_1.bmp")
resource(bitmap_2_1_exif "resources/bitmap_2_1.exif")
resource(bitmap_2_1_gif "resources/bitmap_2_1.gif")
resource(bitmap_2_1_jpg "resources/bitmap_2_1.jpg")
resource(bitmap_2_1_png "resources/bitmap_2_1.png")
resource(bitmap_2_1_pnm "resources/bitmap_2_1.pnm")
resource(bitmap_2_1_ppm "resources/bitmap_2_1.ppm")
resource(bitmap_2_1_tiff "resources/bitmap_2_1.tiff")
resource(bitmap_2_1_xpm "resources/bitmap_2_1.xpm")

# bitmap 2 x 2 :
resource(bitmap_2_2_bmp "resources/bitmap_2_2.bmp")
resource(bitmap_2_2_exif "resources/bitmap_2_2.exif")
resource(bitmap_2_2_gif "resources/bitmap_2_2.gif")
resource(bitmap_2_2_jpg "resources/bitmap_2_2.jpg")
resource(bitmap_2_2_png "resources/bitmap_2_2.png")
resource(bitmap_2_2_pnm "resources/bitmap_2_2.pnm")
resource(bitmap_2_2_ppm "resources/bitmap_2_2.ppm")
resource(bitmap_2_2_tiff "resources/bitmap_2_2.tiff")
resource(bitmap_2_2_xpm "resources/bitmap_2_2.xpm")

# bitmap 2 x 3 :
resource(bitmap_2_3_bmp "resources/bitmap_2_3.bmp")
resource(bitmap_2_3_exif "resources/bitmap_2_3.exif")
resource(bitmap_2_3_gif "resources/bitmap_2_3.gif")
resource(bitmap_2_3_jpg "resources/bitmap_2_3.jpg")
resource(bitmap_2_3_png "resources/bitmap_2_3.png")
resource(bitmap_2_3_pnm "resources/bitmap_2_3.pnm")
resource(bitmap_2_3_ppm "resources/bitmap_2_3.ppm")
resource(bitmap_2_3_tiff "resources/bitmap_2_3.tiff")
resource(bitmap_2_3_xpm "resources/bitmap_2_3.xpm")

# bitmap 2 x 4 :
resource(bitmap_2_4_bmp "resources/bitmap_2_4.bmp")
resource(bitmap_2_4_exif "resources/bitmap_2_4.exif")
resource(bitmap_2_4_gif "resources/bitmap_2_4.gif")
resource(bitmap_2_4_jpg "resources/bitmap_2_4.jpg")
resource(bitmap_2_4_png "resources/bitmap_2_4.png")
resource(bitmap_2_4_pnm "resources/bitmap_2_4.pnm")
resource(bitmap_2_4_ppm "resources/bitmap_2_4.ppm")
resource(bitmap_2_4_tiff "resources/bitmap_2_4.tiff")
resource(bitmap_2_4_xpm "resources/bitmap_2_4.xpm")

# bitmap 3 x 1 :
resource(bitmap_3_1_bmp "resources/bitmap_3_1.bmp")
resource(bitmap_3_1_exif "resources/bitmap_3_1.exif")
resource(bitmap_3_1_gif "resources/bitmap_3_1.gif")
resource(bitmap_3_1_jpg "resources/bitmap_3_1.jpg")
resource(bitmap_3_1_png "resources/bitmap_3_1.png")
resource(bitmap_3_1_pnm "resources/bitmap_3_1.pnm")
resource(bitmap_3_1_ppm "resources/bitmap_3_1.ppm")
resource(bitmap_3_1_tiff "resources/bitmap_3_1.tiff")
resource(bitmap_3_1_xpm "resources/bitmap_3_1.xpm")

# bitmap 3 x 2 :
resource(bitmap_3_2_bmp "resources/bitmap_3_2.bmp")
resource(bitmap_3_2_exif "resources/bitmap_3_2.exif")
resource(bitmap_3_2_gif "resources/bitmap_3_2.gif")
resource(bitmap_3_2_jpg "resources/bitmap_3_2.jpg")
resource(bitmap_3_2_png "resources/bitmap_3_2.png")
resource(bitmap_3_2_pnm "resources/bitmap_3_2.pnm")
resource(bitmap_3_2_ppm "resources/bitmap_3_2.ppm")
resource(bitmap_3_2_tiff "resources/bitmap_3_2.tiff")
resource(bitmap_3_2_xpm "resources/bitmap_3_2.xpm")

# bitmap 3 x 3 :
resource(bitmap_3_3_bmp "resources/bitmap_3_3.bmp")
resource(bitmap_3_3_exif "resources/bitmap_3_3.exif")
resource(bitmap_3_3_gif "resources/bitmap_3_3.gif")
resource(bitmap_3_3_jpg "resources/bitmap_3_3.jpg")
resource(bitmap_3_3_png "resources/bitmap_3_3.png")
resource(bitmap_3_3_pnm "resources/bitmap_3_3.pnm")
resource(bitmap_3_3_ppm "resources/bitmap_3_3.ppm")
resource(bitmap_3_3_tiff "resources/bitmap_3_3.tiff")
resource(bitmap_3_3_xpm "resources/bitmap_3_3.xpm")

# bitmap 3 x 4 :
resource(bitmap_3_4_bmp "resources/bitmap_3_4.bmp")
resource(bitmap_3_4_exif "resources/bitmap_3_4.exif")
resource(bitmap_3_4_gif "resources/bitmap_3_4.gif")
resource(bitmap_3_4_jpg "resources/bitmap_3_4.jpg")
resource(bitmap_3_4_png "resources/bitmap_3_4.png")
resource(bitmap_3_4_pnm "resources/bitmap_3_4.pnm")
resource(bitmap_3_4_ppm "resources/bitmap_3_4.ppm")
resource(bitmap_3_4_tiff "resources/bitmap_3_4.tiff")
resource(bitmap_3_4_xpm "resources/bitmap_3_4.xpm")

# bitmap 4 x 1 :
resource(bitmap_4_1_bmp "resources/bitmap_4_1.bmp")
resource(bitmap_4_1_exif "resources/bitmap_4_1.exif")
resource(bitmap_4_1_gif "resources/bitmap_4_1.gif")
resource(bitmap_4_1_jpg "resources/bitmap_4_1.jpg")
resource(bitmap_4_1_png "resources/bitmap_4_1.png")
resource(bitmap_4_1_pnm "resources/bitmap_4_1.pnm")
resource(bitmap_4_1_ppm "resources/bitmap_4_1.ppm")
resource(bitmap_4_1_tiff "resources/bitmap_4_1.tiff")
resource(bitmap_4_1_xpm "resources/bitmap_4_1.xpm")

# bitmap 4 x 2 :
resource(bitmap_4_2_bmp "resources/bitmap_4_2.bmp")
resource(bitmap_4_2_exif "resources/bitmap_4_2.exif")
resource(bitmap_4_2_gif "resources/bitmap_4_2.gif")
resource(bitmap_4_2_jpg "resources/bitmap_4_2.jpg")
resource(bitmap_4_2_png "resources/bitmap_4_2.png")
resource(bitmap_4_2_pnm "resources/bitmap_4_2.pnm")
resource(bitmap_4_2_ppm "resources/bitmap_4_2.ppm")
resource(bitmap_4_2_tiff "resources/bitmap_4_2.tiff")
resource(bitmap_4_2_xpm "resources/bitmap_4_2.xpm")

# bitmap 4 x 3 :
resource(bitmap_4_3_bmp "resources/bitmap_4_3.bmp")
resource(bitmap_4_3_exif "resources/bitmap_4_3.exif")
resource(bitmap_4_3_gif "resources/bitmap_4_3.gif")
resource(bitmap_4_3_jpg "resources/bitmap_4_3.jpg")
resource(bitmap_4_3_png "resources/bitmap_4_3.png")
resource(bitmap_4_3_pnm "resources/bitmap_4_3.pnm")
resource(bitmap_4_3_ppm "resources/bitmap_4_3.ppm")
resource(bitmap_4_3_tiff "resources/bitmap_4_3.tiff")
resource(bitmap_4_3_xpm "resources/bitmap_4_3.xpm")

# bitmap 4 x 4 :
resource(bitmap_4_4_bmp "resources/bitmap_4_4.bmp")
resource(bitmap_4_4_exif "resources/bitmap_4_4.exif")
resource(bitmap_4_4_gif "resources/bitmap_4_4.gif")
resource(bitmap_4_4_jpg "resources/bitmap_4_4.jpg")
resource(bitmap_4_4_png "resources/bitmap_4_4.png")
resource(bitmap_4_4_pnm "resources/bitmap_4_4.pnm")
resource(bitmap_4_4_ppm "resources/bitmap_4_4.ppm")
resource(bitmap_4_4_tiff "resources/bitmap_4_4.tiff")
resource(bitmap_4_4_xpm "resources/bitmap_4_4.xpm")
