#pragma once
#include <xtd/array>
#include <xtd/u32string>

inline static const auto xtd_text = xtd::array<xtd::u32string> {
  U"xtd",
  U"---",
  U"",
  U"Write Once, Run Everywhere!",
  U"",
  U"xtd (pronounced \"extend\") is a modern C++20 framework for creating console (CLI), forms (GUI) and unit test (xUnit) multiplatform applications and libraries.",
  U"",
  U"________________________________________________________________________________________________________________________________________________________________",
  U"Latest news",
  U"",
  U"  • xtd 1.0.0 will require C++20 as the minimum standard - Posted on June 15, 2025",
  U"  • Release xtd 0.1.2 (beta) - Posted on March 12, 2024",
  U"  • The xtd 1.0.0 (beta) is growing - Posted on November 12, 2023",
  U"  • Release xtd 0.1.1 (beta) - Posted on Jully 17, 2023",
  U"  • All news",
  U"",
  U"________________________________________________________________________________________________________________________________________________________________",
  U"Features",
  U"",
  U"  • Free and open-source (MIT License).",
  U"  • A collection of native C++ classes libraries, to complete std.",
  U"  • API close to the .net API with modern C++ approach and full integration with the std standard.",
  U"  • xtd is designed to manage GUI controls and dialogs in pure native mode or with CSS styles.",
  U"  • Written in efficient, modern C++20 with RAII programming idiom.",
  U"  • And highly portable and available on many different platforms (Windows, macOS, Linux, iOS and android).",
  U"  • See features for more informations.",
  U"",
  U"________________________________________________________________________________________________________________________________________________________________",
  U"Objectives and Mission",
  U"",
  U"  • xtd is a powerful, yet easy to use platform to build your applications upon.",
  U"  • xtd is modular and scalable from embedded applications.",
  U"  • xtd provides consistent, comprehensive and comprehensible programming interfaces.",
  U"  • xtd favors simplicity over complexity (\"as simple as possible, but not simpler\").",
  U"  • xtd aims for consistency in design, coding style and documentation.",
  U"  • xtd emphasizes source code quality, in terms of readability, comprehensiveness, consistency, style and testability.",
  U"  • xtd aims to make C++ programming fun again Guiding Principles",
  U"  • Strong focus on code quality, style, consistency and code readability – all code must satisfy our coding style guide.",
  U"  • Strong focus on tests (automated unit tests with high coverage).",
  U"  • Build on top of solid foundations – use existing proven C, C++ or Objective-C libraries (e.g. Win32 APi, Gtk4, AppKit,...) where it makes sense.",
  U"  ",
  U"________________________________________________________________________________________________________________________________________________________________",
  U"Getting started",
  U"",
  U"  • Installation provides download and install documentation.",
  U"  • Guides provides xtd guides and tutorials.",
  U"  • Examples provides over 900 examples to help you use xtd, grouped by libraries and topics."
};
