// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

/// @file
/// @brief Contains drawing_native_export_ keyword.
#pragma once

#if defined(WIN32)
#  if defined(XTD_DRAWING_NATIVE_WXWIDGETS_EXPORT)
#    define drawing_native_export_ __declspec(dllexport)
#  else
#    define drawing_native_export_ __declspec(dllimport)
#  endif
#else
#  if defined(XTD_DRAWING_NATIVE_WXWIDGETS_EXPORT)
#    define drawing_native_export_ __attribute__((visibility ("default")))
#  else
#    define drawing_native_export_
#  endif
#endif
