/// @file
/// @brief Contains xtd::tunit::unit_test class.
#pragma once

/// @defgroup tunit tunit
/// @brief tunit unit test library

#include "abort_error.h"
#include "assert.h"
#include "assert_error.h"
#include "assume.h"
#include "base_assert.h"
#include "class_cleanup_attribute.h"
#include "class_event_args.h"
#include "class_initialize_attribute.h"
#include "collection_assert.h"
#include "collection_assume.h"
#include "collection_valid.h"
#include "console_unit_test.h"
#include "default_insert_basic_ostream_operator.h"
#include "default_main.h"
#include "directory_assert.h"
#include "directory_assume.h"
#include "directory_valid.h"
#include "event_listener.h"
#include "file_assert.h"
#include "file_assume.h"
#include "file_valid.h"
#include "ignore_error.h"
#include "line_info.h"
#include "ostream_event_listener.h"
#include "ostream_unit_test.h"
#include "registered_test_class.h"
#include "settings.h"
#include "string_assert.h"
#include "string_assume.h"
#include "string_valid.h"
#include "test.h"
#include "test_class.h"
#include "test_class_attribute.h"
#include "test_cleanup_attribute.h"
#include "test_event_args.h"
#include "test_initialize_attribute.h"
#include "test_method_attribute.h"
#include "test_state.h"
#include "tunit_event_args.h"
#include "unit_test.h"
#include "valid.h"
