/// @file
/// @brief Contains xtd.tunit library headers.
/// @copyright Copyright (c) 2021 Gammasoft. All rights reserved.
#pragma once

#include <xtd/xtd.core.h>

#include "tunit/abort_error.h"
#include "tunit/assert.h"
#include "tunit/assert_error.h"
#include "tunit/assume.h"
#include "tunit/base_assert.h"
#include "tunit/class_cleanup_attribute.h"
#include "tunit/class_event_args.h"
#include "tunit/class_initialize_attribute.h"
#include "tunit/collection_assert.h"
#include "tunit/collection_assume.h"
#include "tunit/collection_valid.h"
#include "tunit/console_unit_test.h"
#include "tunit/default_insert_basic_ostream_operator.h"
#include "tunit/default_main.h"
#include "tunit/directory_assert.h"
#include "tunit/directory_assume.h"
#include "tunit/directory_valid.h"
#include "tunit/event_listener.h"
#include "tunit/file_assert.h"
#include "tunit/file_assume.h"
#include "tunit/file_valid.h"
#include "tunit/ignore_error.h"
#include "tunit/ostream_event_listener.h"
#include "tunit/ostream_unit_test.h"
#include "tunit/registered_test_class.h"
#include "tunit/settings.h"
#include "tunit/string_assert.h"
#include "tunit/string_assume.h"
#include "tunit/string_valid.h"
#include "tunit/test.h"
#include "tunit/test_class.h"
#include "tunit/test_class_attribute.h"
#include "tunit/test_cleanup_attribute.h"
#include "tunit/test_event_args.h"
#include "tunit/test_initialize_attribute.h"
#include "tunit/test_method_attribute.h"
#include "tunit/test_state.h"
#include "tunit/tunit_event_args.h"
#include "tunit/unit_test.h"
#include "tunit/valid.h"
