#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../src/main_form.h"
#include <xtd/startup.h>

startup_(guidgen_gui::main_form);
#pragma endregion
