target_categories(Development)
target_default_namespace("keycodes")
target_icon(resources/keycodes)
target_name("keycodes")
target_display(ON)
target_startup("keycodes::main_form::main" src/main_form.h)
