/// @file
/// @brief Contains xtd::generic_event_handler event handler.
/// @copyright Copyright (c) 2025 Gammasoft. All rights reserved.
#pragma once
#include "delegate.hpp"
#include "event.hpp"
#include "event_args.hpp"

/// @brief The xtd namespace contains all fundamental classes to access Hardware, Os, System, and more.
namespace xtd {

  /// @brief Represents the method that will handle an event when the event provides data.
  /// ```cpp
  /// template<class event_args_t = const xtd::event_args&>
  /// using generic_event_handler = xtd::delegate<void(xtd::object& sender, event_args_t e)>;
  /// ```
  /// @tparam event_args_t The type of the event data generated by the event.
  /// @param sender The source of the event.
  /// @param e An object that contains the event data.
  /// @par Header
  /// ```cpp
  /// #include <xtd/generic_event_handler>
  /// ```
  /// @par Namespace
  /// xtd
  /// @par Library
  /// xtd.core
  /// @ingroup xtd_core events
  template<class event_args_t>
  using generic_event_handler = xtd::delegate<void(xtd::object& sender, event_args_t e)>;
}
