// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

#pragma once
#include "availability_versions.hpp"

/// @cond
// xtd version

// xtd version definition : major.minor[.build[.revision]]
// * major    : 0 to infinite
// * minor    : 0 to 99
// * build    : 0 to 99
// * revision : 0 to 99

// For example xtd 1.2.3 (major = 1, minor = 2, build = 3 and revision = -1) :
// #define __XTD_VERSION__ 1020300
// #define __XTD_VERSION_MAJOR__ 1
// #define __XTD_VERSION_MINOR__ 2
// #define __XTD_VERSION_BUILD__ 3
// #define __XTD_VERSION_REVISION__ 0
// #define __XTD_VERSION_STRING__ "1.2.3"

#define __XTD_VERSION__ 20000
#define __XTD_VERSION_MAJOR__ 0
#define __XTD_VERSION_MINOR__ 2
#define __XTD_VERSION_BUILD__ 0
#define __XTD_VERSION_REVISION__ 0
#define __XTD_VERSION_STRING__ "0.2.0"
/// @endcond
