#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <xtd/drawing/bitmap>
#include <xtd/drawing/icon>
#include <xtd/io/path>
#include <xtd/environment>
#include <xtd/not_implemented_exception>
#include <xtd/ustring>

namespace image_converter_example::properties {
  /// @brief A strongly-typed resource class, for looking up localized strings, etc.
  /// @details This class was auto-generated by CMake script. To add or remove a member, edit your CMakeList.txt or properties/resources.cmake file then rerun cmake tools.
  /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/resources>Resources</a> for more informations.
  class resources final static_ {
  public:
    /// @brief Looks up a localized resource of type xtd::drawing::bitmap.
    static const xtd::drawing::bitmap& pineapple() {
      static auto bitmap = xtd::drawing::bitmap {xtd::io::path::combine(xtd::io::path::get_directory_name(xtd::environment::get_command_line_args()[0]), "..", "Resources", "pineapple.jpg")};
      return bitmap;
    }

    /// @brief Looks up a localized resource of type xtd::drawing::bitmap.
    static const xtd::drawing::bitmap& rose() {
      static auto bitmap = xtd::drawing::bitmap {xtd::io::path::combine(xtd::io::path::get_directory_name(xtd::environment::get_command_line_args()[0]), "..", "Resources", "rose.jpg")};
      return bitmap;
    }

  };
}

#pragma endregion
