#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Remarks : If this file was manually created, you need re-run cmake generator after creating
//           or modifying any parameter bellow.

#include <xtd/reflection/assembly_info.h>

// Information about this assembly is defined by the following attributes.
// Change them to the values specific to your project.

assembly_title_("xtd.forms.native.fltk");
assembly_description_("xtd.forms.native.fltk library is based on Fltk toolkit.");
assembly_configuration_("");
assembly_company_("Gammasoft");
assembly_product_("xtd.forms.native.fltk");
assembly_copyright_("Copyright © Gammasoft 2024");
assembly_trademark_("");
assembly_culture_("en_US.UTF-8");

// The following GUID is for the ID of the typelib if this project is exposed to COM

assembly_guid_("54540102-0eff-4399-9a42-88d8f7622a26");

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// In not specify or empty or "*" the cmake project version is used.

assembly_version_("");
#pragma endregion
