// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated.

/// @file
/// @brief Contains xtd library headers.
/// @copyright Copyright (c) 2024 Gammasoft. All rights reserved.
#pragma once
#include "xtd/xtd.core"
#include "xtd/xtd.drawing"
#include "xtd/xtd.forms"
#include "xtd/xtd.tunit"
#include "xtd/system_report"
