#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Remarks : If this file was manually created, you need re-run cmake generator after creating
//           or modifying any parameter bellow.

#include <xtd/reflection/assembly_info>

// Information about this assembly is defined by the following attributes.
// Change them to the values specific to your project.

assembly_title_("Forms with manual assembly information");
assembly_description_("This example shows how to use xtd assembly informations");
assembly_configuration_("Debug");
assembly_company_("Gammasoft");
assembly_product_("form_with_manual_assembly_info");
assembly_copyright_("Copyright © Gammasoft 2023");
assembly_trademark_("");
assembly_culture_("");

// The following GUID is for the ID of the typelib if this project is exposed to COM

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// In not specify or empty or "*" the cmake project version is used.

assembly_version_("1.0.0");
#pragma endregion
