#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <xtd/xtd>

namespace settings_command::properties {
  class settings : public xtd::forms::component {
  public:
    settings() : ::settings_command::properties::settings(true) {}

    static ::settings_command::properties::settings& default_settings() {
      static ::settings_command::properties::settings default_settings;
      return default_settings;
    }

    xtd::drawing::color color() const {return color_;}
    void color(xtd::drawing::color value) {color_ = value;}

    void reload() {
      color_ = settings_.read("color", color_);
    }

    void reset() {
      settings_.reset();
      *this = settings(false);
      reload();
    }

    void save() {
      settings_.write("color", color_);
      settings_.save();
    }

  private:
    settings(bool load) {if (load) reload();}
    xtd::forms::settings settings_;
    xtd::drawing::color color_ {xtd::drawing::color::red};
  };
}

#pragma endregion
