#include <xtd/console>
#include <xtd/forms/loading_indicator_style.h>

using namespace xtd;
using namespace xtd::forms;

auto main()->int {
  //console::write_line("Core manual test");
  for (auto name : enum_object<>::get_names<loading_indicator_style>()) {
    console::write_line("loading_indicator loading_indicators::{}() {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const xtd::drawing::point& location) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.location(location);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const xtd::drawing::point& location, const xtd::drawing::size& size) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const xtd::drawing::point& location, const xtd::drawing::size& size, const xtd::ustring& name) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  result.name(name);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(bool running) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.running(running);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(bool running, const xtd::drawing::point& location) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.running(running);");
    console::write_line("  result.location(location);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(bool running, const xtd::drawing::point& location, const xtd::drawing::size& size) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.running(running);");
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(bool running, const xtd::drawing::point& location, const xtd::drawing::size& size, const xtd::ustring& name) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.running(running);");
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  result.name(name);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent, const xtd::drawing::point& location) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  result.location(location);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent, const xtd::drawing::point& location, const xtd::drawing::size& size) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent, const xtd::drawing::point& location, const xtd::drawing::size& size, const xtd::ustring& name) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  result.name(name);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent, bool running) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  result.running(running);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent, bool running, const xtd::drawing::point& location) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  result.running(running);");
    console::write_line("  result.location(location);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent, bool running, const xtd::drawing::point& location, const xtd::drawing::size& size) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  result.running(running);");
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
    console::write_line("loading_indicator loading_indicators::{}(const control& parent, bool running, const xtd::drawing::point& location, const xtd::drawing::size& size, const xtd::ustring& name) {{", name);
    console::write_line("  auto result = loading_indicator {};");
    console::write_line("  result.loading_indicator_style(xtd::forms::loading_indicator_style::{});", name);
    console::write_line("  result.parent(parent);");
    console::write_line("  result.running(running);");
    console::write_line("  result.location(location);");
    console::write_line("  result.size(size);");
    console::write_line("  result.name(name);");
    console::write_line("  return result;");
    console::write_line("}");
    console::write_line();
  }
}
