#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Remarks : If this file was manually created, you need re-run cmake generator after creating
//           or modifying any parameter bellow.

#include <xtd/reflection/assembly_info>

// Information about this assembly is defined by the following attributes.
// Change them to the values specific to your project.

assembly_title_("xtd.forms.labels.tests");
assembly_description_("xtd.forms.labels.tests contains xtd::forms::label manual tests.");
assembly_configuration_("Test");
assembly_company_("Gammasoft");
assembly_product_("xtd.forms.labels.tests");
assembly_copyright_("Copyright © Gammasoft 2023");
assembly_trademark_("");
assembly_culture_("en_US.UTF-8");

// The following GUID is for the ID of the typelib if this project is exposed to COM

assembly_guid_("c387ae26-2946-4754-984b-918f80ff8af2");

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// In not specify or empty or "*" the cmake project version is used.

assembly_version_("");
#pragma endregion
