#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <xtd/drawing/bitmap>
#include <xtd/drawing/icon>
#include <xtd/io/path>
#include <xtd/environment>
#include <xtd/not_implemented_exception>
#include <xtd/string>

namespace stopwatch_form::properties {
  /// @brief A strongly-typed resource class, for looking up localized strings, etc.
  /// @details This class was auto-generated by CMake script. To add or remove a member, edit your CMakeList.txt or properties/resources.cmake file then rerun cmake tools.
  /// @remarks See [Resources](https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/resources) for more informations.
  class resources final static_ {
  public:
    /// @name Public Static Properties

    /// @{
    /// @brief Looks up a localized resource of type xtd::drawing::icon.
    static const xtd::drawing::icon& stopwatch_ico() {
      static auto icon = xtd::drawing::icon {xtd::io::path::combine(xtd::environment::get_folder_path(xtd::environment::special_folder::application_resources), "stopwatch.ico")};
      return icon;
    }

    /// @}
  };
}

#pragma endregion
