/// @file
/// @brief Contains xtd::tunit::unit_test class.
#pragma once
#define _CRT_SECURE_NO_WARNINGS

/// @defgroup tunit tunit
/// @brief tunit unit test library

#include "abort_error.hpp"
#include "assert.hpp"
#include "assert_error.hpp"
#include "assume.hpp"
#include "base_assert.hpp"
#include "class_cleanup_attribute.hpp"
#include "class_event_args.hpp"
#include "class_initialize_attribute.hpp"
#include "collection_assert.hpp"
#include "collection_assume.hpp"
#include "collection_valid.hpp"
#include "console_unit_test.hpp"
#include "default_insert_basic_ostream_operator.hpp"
#include "default_main.hpp"
#include "directory_assert.hpp"
#include "directory_assume.hpp"
#include "directory_valid.hpp"
#include "event_listener.hpp"
#include "file_assert.hpp"
#include "file_assume.hpp"
#include "file_valid.hpp"
#include "ignore_error.hpp"
#include "line_info.hpp"
#include "ostream_event_listener.hpp"
#include "ostream_unit_test.hpp"
#include "registered_test_class.hpp"
#include "settings.hpp"
#include "string_assert.hpp"
#include "string_assume.hpp"
#include "string_valid.hpp"
#include "test.hpp"
#include "test_class.hpp"
#include "test_class_attribute.hpp"
#include "test_cleanup_attribute.hpp"
#include "test_event_args.hpp"
#include "test_initialize_attribute.hpp"
#include "test_method_attribute.hpp"
#include "test_state.hpp"
#include "tunit_event_args.hpp"
#include "unit_test.hpp"
#include "valid.hpp"
