#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../src/ball.hpp"
#include <xtd/startup>

auto main(int argc, char* argv[]) -> int {
  return xtd::startup::safe_run(ball::main_form::main, argc, argv);
}
#pragma endregion
