#include <xtd/diagnostics/debugger>
#include <xtd/forms/animation>
#include <xtd/forms/form>
#include <xtd/tunit/assert>
#include <xtd/tunit/test_class_attribute>
#include <xtd/tunit/test_method_attribute>

using namespace xtd;
using namespace xtd::drawing;
using namespace xtd::forms;
using namespace xtd::tunit;

namespace xtd::forms::tests {
  class test_class_(animation_tests) {
    class animation_for_test : public animation {
    public:
      animation_for_test() = default;
      
      using animation::default_back_color;
      using animation::default_cursor;
      using animation::default_font;
      using animation::default_fore_color;
      using animation::default_size;
    };
    
    auto test_method_(constructor) {
      animation_for_test animation;
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::are_equal(animation.default_size().height, animation.bottom());
      assert::are_equal(drawing::rectangle({0, 0}, animation.default_size()), animation.bounds());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal(drawing::rectangle({0, 0}, animation.default_size()), animation.client_rectangle());
      assert::are_equal(animation.default_size(), animation.client_size());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_false(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.default_back_color());
      assert::are_equal(forms::cursors::default_cursor(), animation.default_cursor());
      assert::are_equal(drawing::system_fonts::default_font(), animation.default_font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.default_fore_color());
      assert::are_equal(animation.default_size(), animation.default_size());
      assert::are_equal(drawing::rectangle({0, 0}, animation.default_size()), animation.display_rectangle());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_zero(animation.handle());
      assert::are_equal(animation.default_size().height, animation.height());
      assert::is_false(animation.invoke_required());
      assert::is_false(animation.is_handle_created());
      assert::is_zero(animation.left());
      assert::are_equal(drawing::point::empty, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::is_null(animation.parent());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::are_equal(animation.default_size().width, animation.right());
      assert::are_equal(animation.default_size(), animation.size());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_zero(animation.toolkit_handle());
      assert::is_zero(animation.top());
      assert::is_null(animation.top_level_control());
      assert::is_true(animation.visible());
      assert::are_equal(animation.default_size().width, animation.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(10u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create) {
      auto animation = forms::animation::create();
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_false(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_zero(animation.handle());
      assert::is_false(animation.invoke_required());
      assert::is_false(animation.is_handle_created());
      assert::is_zero(animation.left());
      assert::are_equal(drawing::point::empty, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::is_null(animation.parent());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_zero(animation.toolkit_handle());
      assert::is_zero(animation.top());
      assert::is_null(animation.top_level_control());
      assert::is_true(animation.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(10u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_frame_per_second) {
      auto animation = forms::animation::create(60);
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_false(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_zero(animation.handle());
      assert::is_false(animation.invoke_required());
      assert::is_false(animation.is_handle_created());
      assert::is_zero(animation.left());
      assert::are_equal(drawing::point::empty, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::is_null(animation.parent());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_zero(animation.toolkit_handle());
      assert::is_zero(animation.top());
      assert::is_null(animation.top_level_control());
      assert::is_true(animation.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_frame_per_second_and_location) {
      auto animation = forms::animation::create(60, {10, 20});
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_false(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_zero(animation.handle());
      assert::is_false(animation.invoke_required());
      assert::is_false(animation.is_handle_created());
      assert::are_equal(10, animation.left());
      assert::are_equal(point {10, 20}, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::is_null(animation.parent());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_zero(animation.toolkit_handle());
      assert::are_equal(20, animation.top());
      assert::is_null(animation.top_level_control());
      assert::is_true(animation.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_frame_per_second_location_and_size) {
      auto animation = forms::animation::create(60, {10, 20}, {30, 40});
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_false(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_zero(animation.handle());
      assert::are_equal(40, animation.height());
      assert::is_false(animation.invoke_required());
      assert::is_false(animation.is_handle_created());
      assert::are_equal(10, animation.left());
      assert::are_equal(point {10, 20}, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::is_null(animation.parent());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::are_equal(drawing::size {30, 40}, animation.size());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_zero(animation.toolkit_handle());
      assert::are_equal(20, animation.top());
      assert::is_null(animation.top_level_control());
      assert::is_true(animation.visible());
      assert::are_equal(30, animation.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_frame_per_second_location_size_and_name) {
      auto animation = forms::animation::create(60, {10, 20}, {30, 40}, "animation");
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_false(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_zero(animation.handle());
      assert::are_equal(40, animation.height());
      assert::is_false(animation.invoke_required());
      assert::is_false(animation.is_handle_created());
      assert::are_equal(10, animation.left());
      assert::are_equal(point {10, 20}, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_zero(animation.native_handle());
      assert::are_equal("animation", animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::is_null(animation.parent());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::are_equal(drawing::size {30, 40}, animation.size());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_zero(animation.toolkit_handle());
      assert::are_equal(20, animation.top());
      assert::is_null(animation.top_level_control());
      assert::is_true(animation.visible());
      assert::are_equal(30, animation.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_parent) {
      auto form = forms::form::create();
      auto animation = forms::animation::create(form);
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_true(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_not_zero(animation.handle());
      assert::is_false(animation.invoke_required());
      assert::is_true(animation.is_handle_created());
      assert::is_zero(animation.left());
      assert::are_equal(drawing::point::empty, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_not_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::are_same(form, animation.parent().value().get());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_not_zero(animation.toolkit_handle());
      assert::is_zero(animation.top());
      assert::are_same(form, animation.top_level_control().value().get());
      assert::is_true(animation.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(10u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_parent_and_frame_per_second) {
      auto form = forms::form::create();
      auto animation = forms::animation::create(form, 60);
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_true(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_not_zero(animation.handle());
      assert::is_false(animation.invoke_required());
      assert::is_true(animation.is_handle_created());
      assert::is_zero(animation.left());
      assert::are_equal(drawing::point::empty, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_not_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::are_same(form, animation.parent().value().get());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_not_zero(animation.toolkit_handle());
      assert::is_zero(animation.top());
      assert::are_same(form, animation.top_level_control().value().get());
      assert::is_true(animation.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_parent_frame_per_second_and_location) {
      auto form = forms::form::create();
      auto animation = forms::animation::create(form, 60, {10, 20});
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_true(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_not_zero(animation.handle());
      assert::is_false(animation.invoke_required());
      assert::is_true(animation.is_handle_created());
      assert::are_equal(10, animation.left());
      assert::are_equal(point {10, 20}, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_not_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::are_same(form, animation.parent().value().get());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_not_zero(animation.toolkit_handle());
      assert::are_equal(20, animation.top());
      assert::are_same(form, animation.top_level_control().value().get());
      assert::is_true(animation.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_parent_frame_per_second_location_and_size) {
      auto form = forms::form::create();
      auto animation = forms::animation::create(form, 60, {10, 20}, {30, 40});
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_true(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_not_zero(animation.handle());
      assert::are_equal(40, animation.height());
      assert::is_false(animation.invoke_required());
      assert::is_true(animation.is_handle_created());
      assert::are_equal(10, animation.left());
      assert::are_equal(point {10, 20}, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_not_zero(animation.native_handle());
      assert::is_empty(animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::are_same(form, animation.parent().value().get());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::are_equal(drawing::size {30, 40}, animation.size());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_not_zero(animation.toolkit_handle());
      assert::are_equal(20, animation.top());
      assert::are_same(form, animation.top_level_control().value().get());
      assert::is_true(animation.visible());
      assert::are_equal(30, animation.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
    
    auto test_method_(create_with_parent_frame_per_second_location_size_and_name) {
      auto form = forms::form::create();
      auto animation = forms::animation::create(form, 60, {10, 20}, {30, 40}, "animation");
      assert::are_equal(anchor_styles::left | anchor_styles::top, animation.anchor());
      assert::are_equal(drawing::point::empty, animation.auto_scroll_point());
      assert::is_false(animation.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), animation.back_color());
      assert::are_equal(drawing::image::empty, animation.background_image());
      assert::are_equal(image_layout::tile, animation.background_image_layout());
      assert::is_false(animation.can_focus());
      assert::is_true(animation.can_raise_events());
      assert::is_true(animation.can_select());
      assert::are_equal("Gammasoft", animation.company_name());
      assert::is_null(animation.context_menu());
      assert::are_equal(forms::control_appearance::standard, animation.control_appearance());
      assert::is_empty(animation.controls());
      assert::is_true(animation.created());
      assert::are_equal(forms::cursors::default_cursor(), animation.cursor());
      assert::are_equal(forms::dock_style::none, animation.dock());
      assert::is_true(animation.double_buffered());
      assert::is_true(animation.enabled());
      assert::is_false(animation.focused());
      assert::are_equal(drawing::system_fonts::default_font(), animation.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), animation.fore_color());
      assert::is_not_zero(animation.handle());
      assert::are_equal(40, animation.height());
      assert::is_false(animation.invoke_required());
      assert::is_true(animation.is_handle_created());
      assert::are_equal(10, animation.left());
      assert::are_equal(point {10, 20}, animation.location());
      assert::are_equal(forms::padding(3), animation.margin());
      assert::are_equal(drawing::size::empty, animation.maximum_client_size());
      assert::are_equal(drawing::size::empty, animation.maximum_size());
      assert::are_equal(drawing::size::empty, animation.minimum_client_size());
      assert::are_equal(drawing::size::empty, animation.minimum_size());
      assert::is_not_zero(animation.native_handle());
      assert::are_equal("animation", animation.name());
      assert::are_equal(forms::padding(0), animation.padding());
      assert::are_same(form, animation.parent().value().get());
      assert::are_equal("xtd", animation.product_name());
      assert::is_not_zero(animation.region().handle());
      assert::are_equal(drawing::size {30, 40}, animation.size());
      assert::is_empty(animation.style_sheet().theme().name());
      assert::is_true(animation.tab_stop());
      assert::is_false(animation.tag().has_value());
      assert::is_empty(animation.text());
      assert::is_not_zero(animation.toolkit_handle());
      assert::are_equal(20, animation.top());
      assert::are_same(form, animation.top_level_control().value().get());
      assert::is_true(animation.visible());
      assert::are_equal(30, animation.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_zero(animation.elapsed());
      assert::is_zero(animation.elapsed_milliseconds());
      assert::is_zero(animation.elapsed_nanoseconds());
      assert::is_zero(animation.elapsed_ticks());
      assert::is_zero(animation.frame_counter());
      assert::are_equal(60u, animation.frames_per_second());
      assert::is_false(animation.running());
    }
  };
}
