#include <xtd/diagnostics/debugger>
#include <xtd/forms/command_link_button>
#include <xtd/forms/form>
#include <xtd/tunit/assert>
#include <xtd/tunit/test_class_attribute>
#include <xtd/tunit/test_method_attribute>

using namespace xtd;
using namespace xtd::drawing;
using namespace xtd::forms;
using namespace xtd::tunit;

namespace xtd::forms::tests {
  class test_class_(command_link_button_tests) {
    class command_link_button_for_test : public command_link_button {
    public:
      command_link_button_for_test() = default;
      
      using command_link_button::default_back_color;
      using command_link_button::default_cursor;
      using command_link_button::default_font;
      using command_link_button::default_fore_color;
      using command_link_button::default_size;
    };
    
    auto test_method_(constructor) {
      command_link_button_for_test command_link_button;
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::are_equal(command_link_button.default_size().height, command_link_button.bottom());
      assert::are_equal(drawing::rectangle({0, 0}, command_link_button.default_size()), command_link_button.bounds());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal(drawing::rectangle({0, 0}, command_link_button.default_size()), command_link_button.client_rectangle());
      assert::are_equal(command_link_button.default_size(), command_link_button.client_size());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.default_back_color());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.default_cursor());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.default_font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.default_fore_color());
      assert::are_equal(command_link_button.default_size(), command_link_button.default_size());
      assert::are_equal(drawing::rectangle({0, 0}, command_link_button.default_size()), command_link_button.display_rectangle());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::are_equal(command_link_button.default_size().height, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::is_zero(command_link_button.left());
      assert::are_equal(drawing::point::empty, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(command_link_button.default_size().width, command_link_button.right());
      assert::are_equal(command_link_button.default_size(), command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::is_empty(command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::is_zero(command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(command_link_button.default_size().width, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create) {
      auto command_link_button = forms::command_link_button::create();
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::is_zero(command_link_button.left());
      assert::are_equal(drawing::point::empty, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::is_empty(command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::is_zero(command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_text) {
      auto command_link_button = forms::command_link_button::create("new text");
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::is_zero(command_link_button.left());
      assert::are_equal(drawing::point::empty, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::is_zero(command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_text_and_location) {
      auto command_link_button = forms::command_link_button::create("new text", drawing::point {10, 20});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_text_location_and_size) {
      auto command_link_button = forms::command_link_button::create("new text", drawing::point {10, 20}, drawing::size {30, 40});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_text_location_size_and_name) {
      auto command_link_button = forms::command_link_button::create("new text", {10, 20}, {30, 40}, "command_link_button");
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::are_equal("command_link_button", command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_texts) {
      auto command_link_button = forms::command_link_button::create(std::make_tuple("new text", "other"));
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::is_zero(command_link_button.left());
      assert::are_equal(drawing::point::empty, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::is_zero(command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_texts_and_location) {
      auto command_link_button = forms::command_link_button::create(std::make_tuple("new text", "other"), drawing::point {10, 20});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_texts_location_and_size) {
      auto command_link_button = forms::command_link_button::create(std::make_tuple("new text", "other"), drawing::point {10, 20}, drawing::size {30, 40});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_texts_location_size_and_name) {
      auto command_link_button = forms::command_link_button::create(std::make_tuple("new text", "other"), {10, 20}, {30, 40}, "command_link_button");
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_false(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_false(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_zero(command_link_button.native_handle());
      assert::are_equal("command_link_button", command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::is_null(command_link_button.parent());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::is_null(command_link_button.top_level_control());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form);
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::is_zero(command_link_button.left());
      assert::are_equal(drawing::point::empty, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::is_empty(command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::is_zero(command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_and_text) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, "new text");
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::is_zero(command_link_button.left());
      assert::are_equal(drawing::point::empty, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::is_zero(command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_text_and_location) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, "new text", drawing::point {10, 20});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_text_location_and_size) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, "new text", drawing::point {10, 20}, drawing::size {30, 40});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_text_location_size_and_name) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, "new text", {10, 20}, {30, 40}, "command_link_button");
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::are_equal("command_link_button", command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_texts) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, std::make_tuple("new text", "other"));
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::is_zero(command_link_button.left());
      assert::are_equal(drawing::point::empty, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::is_zero(command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_texts_and_location) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, std::make_tuple("new text", "other"), drawing::point {10, 20});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_texts_location_and_size) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, std::make_tuple("new text", "other"), drawing::point {10, 20}, drawing::size {30, 40});
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::is_empty(command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(create_with_parent_texts_location_size_and_name) {
      auto form = forms::form::create();
      auto command_link_button = forms::command_link_button::create(form, std::make_tuple("new text", "other"), {10, 20}, {30, 40}, "command_link_button");
      assert::are_equal(anchor_styles::left | anchor_styles::top, command_link_button.anchor());
      assert::are_equal(drawing::point::empty, command_link_button.auto_scroll_point());
      assert::is_false(command_link_button.auto_size());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control(), command_link_button.back_color());
      assert::are_equal(drawing::image::empty, command_link_button.background_image());
      assert::are_equal(image_layout::tile, command_link_button.background_image_layout());
      assert::is_false(command_link_button.can_focus());
      assert::is_true(command_link_button.can_raise_events());
      assert::is_true(command_link_button.can_select());
      assert::are_equal("Gammasoft", command_link_button.company_name());
      assert::is_null(command_link_button.context_menu());
      assert::are_equal(forms::control_appearance::system, command_link_button.control_appearance());
      assert::is_empty(command_link_button.controls());
      assert::is_true(command_link_button.created());
      assert::are_equal(forms::cursors::default_cursor(), command_link_button.cursor());
      assert::are_equal(forms::dock_style::none, command_link_button.dock());
      assert::is_false(command_link_button.double_buffered());
      assert::is_true(command_link_button.enabled());
      assert::is_false(command_link_button.focused());
      assert::are_equal(drawing::system_fonts::default_font(), command_link_button.font());
      assert::are_equal(style_sheets::style_sheet::current_style_sheet().system_colors().control_text(), command_link_button.fore_color());
      assert::is_not_zero(command_link_button.handle());
      assert::are_equal(40, command_link_button.height());
      assert::is_false(command_link_button.invoke_required());
      assert::is_true(command_link_button.is_handle_created());
      assert::are_equal(10, command_link_button.left());
      assert::are_equal(point {10, 20}, command_link_button.location());
      assert::are_equal(forms::padding(3), command_link_button.margin());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.maximum_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_client_size());
      assert::are_equal(drawing::size::empty, command_link_button.minimum_size());
      assert::is_not_zero(command_link_button.native_handle());
      assert::are_equal("command_link_button", command_link_button.name());
      assert::are_equal(forms::padding(0), command_link_button.padding());
      assert::are_same(form, command_link_button.parent().value().get());
      assert::are_equal("xtd", command_link_button.product_name());
      assert::is_not_zero(command_link_button.region().handle());
      assert::are_equal(drawing::size {30, 40}, command_link_button.size());
      assert::is_empty(command_link_button.style_sheet().theme().name());
      assert::is_true(command_link_button.tab_stop());
      assert::is_false(command_link_button.tag().has_value());
      assert::are_equal("new text\nother", command_link_button.text());
      assert::is_not_zero(command_link_button.toolkit_handle());
      assert::are_equal(20, command_link_button.top());
      assert::are_same(form, command_link_button.top_level_control().value().get());
      assert::is_true(command_link_button.visible());
      assert::are_equal(30, command_link_button.width());
      assert::are_equal(diagnostics::debugger::is_attached(), forms::control::check_for_illegal_cross_thread_calls());
      assert::are_equal(keys::none, forms::control::modifier_keys());
      assert::are_equal(forms::mouse_buttons::none, forms::control::mouse_buttons());
      // The following test may fail: The user can place the mouse in the upper left position of the screen {0, 0}...
      // assert::are_not_equal(drawing::point::empty, forms::control::mouse_position());
      
      assert::is_false(command_link_button.auto_ellipsis());
      assert::are_equal(flat_button_appearance(), command_link_button.flat_appearance());
      assert::are_equal(flat_style::system, command_link_button.flat_style());
      assert::are_equal(image::empty, command_link_button.image());
      assert::are_equal(content_alignment::middle_center, command_link_button.image_align());
      assert::are_equal(-1, command_link_button.image_index());
      assert::are_equal(image_list::empty, command_link_button.image_list());
      assert::are_equal(content_alignment::middle_left, command_link_button.text_align());
    }
    
    auto test_method_(set_client_size) {
      form form;
      command_link_button_for_test command_link_button;
      command_link_button.parent(form);
      command_link_button.client_size({100, 50});
      assert::are_equal(drawing::size(100, 50), command_link_button.client_size());
    }
    
    auto test_method_(set_size) {
      form form;
      command_link_button_for_test command_link_button;
      command_link_button.parent(form);
      command_link_button.size({100, 50});
      assert::are_equal(drawing::size(100, 50), command_link_button.size());
    }
  };
}
