#pragma once
#include <xtd/xtd.strings>
#include "drawing/native/brush.h"
#include "drawing/native/font_family.h"
#include "drawing/native/font.h"
#include "drawing/native/graphics.h"
#include "drawing/native/pen.h"
#include "drawing/native/system_colors.h"
#include "drawing/native/system_fonts.h"
#include "drawing/native/system_images.h"
